version: '3.1'

services:
  tripklikb2c:
    stdin_open: true
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5000:5000"
    build:
      dockerfile: Dockerfile-next-dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - b2c-network

networks:
  b2c-network:
    driver: bridge 