# Use an official Node runtime as a parent image
FROM node:20-alpine

# Create a directory for the app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# install all dependancy
RUN npm i --legacy-peer-deps

# Copy the rest of the app to the container
COPY . .

# Expose the port that the app will run on
EXPOSE 5000


CMD ["npm", "run", "dev", "--" ,"-p", "5000"]